name: Tests
on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      
      - name: Install python
        run: python3 -m pip3 install --upgrade pip pytest
   
      - name: Install requests module
        run: python3 -m pip3 install requests
        
      - name: Install random
        run: python3 -m pip3 install random  

      - name: Test with unittest
        run: |
          python3 -m unittest testFile.py